name: build

on: [push]

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          
        sm_version:
          - "latest"
          
        include:
          - sm_version: latest
            sm_branch: master
            
          - os: ubuntu-latest
            os_short: linux
            
    steps:
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt purge clang
          sudo apt-get install -y gcc-multilib g++-multilib
          
      - name: Setup Sourcemod & HL2SDK
        run: |
          git clone --recursive https://github.com/alliedmodders/sourcemod
          bash sourcemod/tools/checkout-deps.sh
          
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Getting own repository
        uses: actions/checkout@v4
        with:
          path: extension
          
      - name: Compiling ${{ github.event.repository.name }} files
        working-directory: extension
        run: |
          mkdir build
          cd build
          python ../configure.py
          ambuild
          
      - name: Uploading package
        uses: actions/upload-artifact@v4
        with:
          name: sm-ext-yyjson-sm${{ matrix.sm_version }}-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: extension/build/package
